[package]
name = "breezert_socketman"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "breezert_socketman"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
